### ISSUE TITLE
Local JSON file

### ISSUE THREAD

**Issue by TheAndroidGuy** [RKikuchi/charades#1]
Awesome project !
The code is really clean.

I was wondering how easy would it be to use local JSON file instead from the internet ?
Or how could i add more categories and words at (http://restazero.com/charades/) ?

**Comment by RKikuchi** [comment]
Thank you! :)
I should be working on that this weekend.

**Comment by TheAndroidGuy** [comment]
Great :+1:

**Comment by RKikuchi** [comment]
Just pushed this feature (4bd6c592b1ce103d9c9195d727bb4f4af1e96ce0), let me know if there are any problems.

**Comment by TheAndroidGuy** [comment]
Great job :+1: 
Works like a charm :)

**Comment by TheAndroidGuy** [comment]
I have another idea.
The first category could be a "Mixed words". This would pick a random word from random category :)

**Comment by RKikuchi** [comment]
I'll work on that after finishing some other features :)
